#!/bin/bash

#Exercise 2: Write a program that takes 20 NUMbers from the input, compares them, and 
#states which NUMber is the largest and smallest.

read -p "Enter NUMber 1: " NUM
MIN=$NUM
MAX=$NUM

for i in {2..20}; do
    read -p "Enter NUMber $i: " NUM
    if (( NUM < MIN )); then
        MIN=$NUM
    fi
    if (( NUM > MAX )); then
        MAX=$NUM
    fi
done

echo "Smallest NUMber: $MIN"
echo "Largest NUMber: $MAX"

